document.write('<table class="table table-responsive table-bordered pull-left">        ');
document.write('	<thead>                                                            ');
document.write('		<tr><th colspan="6">SIZE CHART (In Inches)</th></tr> ');
document.write('	</thead>                                                           ');
document.write('	<tbody>                                                            ');
document.write('		<tr>                                                           ');
document.write('			<td width="50%">LABEL</td>                                 ');
document.write('			<td width="10%">S</td>                                     ');
document.write('			<td width="10%">M</td>                                     ');
document.write('			<td width="10%">L</td>                                     ');
document.write('			<td width="10%">XL</td>                                    ');
document.write('			<td width="10%">2XL</td>                                   ');
document.write('		</tr>                                                          ');
document.write('		<tr>                                                           ');
document.write('			<td width="50%">CHEST</td>                                 ');
document.write('			<td width="10%">36</td>                                    ');
document.write('			<td width="10%">38</td>                                    ');
document.write('			<td width="10%">40</td>                                    ');
document.write('			<td width="10%">42</td>                                    ');
document.write('			<td width="10%">44</td>                                    ');
document.write('		</tr>                                                          ');
document.write('		<tr>                                                           ');
document.write('			<td width="50%">LENGTH</td>                                ');
document.write('			<td width="10%">25</td>                                    ');
document.write('			<td width="10%">26</td>                                    ');
document.write('			<td width="10%">27</td>                                    ');
document.write('			<td width="10%">28</td>                                    ');
document.write('			<td width="10%">29</td>                                    ');
document.write('		</tr>                                                          ');
document.write('		<tr><th colspan="6">SHIRT/CROSS MEASUREMENT</th></tr>          ');
document.write('		<tr>                                                           ');
document.write('			<td width="50%">SHOULDER</td>                              ');
document.write('			<td width="10%">15</td>                                    ');
document.write('			<td width="10%">16</td>                                    ');
document.write('			<td width="10%">17</td>                                    ');
document.write('			<td width="10%">18</td>                                    ');
document.write('			<td width="10%">19</td>                                    ');
document.write('		</tr>                                                          ');
document.write('	</tbody>                                                           ');
document.write('</table>                                                               ');